def evidence_bundle():
    return {
        "budget": {
            "followup_sample_count": 300,
            "language_sample_counts": {"en": 100, "mixed": 100, "zh_hans": 100},
            "estimator_error_direction": {"over": 300},
            "known_over_budget_provider_calls": 0,
            "mandatory_current_content_losses": 0,
            "would_select_count": 3360,
            "would_drop_count": 1800,
            "fallback_count": 300,
            "baseline_error_rate": 0.0,
            "followup_error_rate": 0.0,
            "baseline_p95_latency_ms": 500.0,
            "followup_p95_latency_ms": 533.252,
            "data_complete": True,
            "unavailable_bucket_count": 0,
            "privacy_audit_hits": 0,
            "budget_config_conflict": False,
            "cleanup_residue": 0,
        },
        "write": {
            "sample_count": 300,
            "proposal_created_count": 300,
            "deduplicated_replay_count": 9,
            "fault_matrix": {
                "candidate_rejected": 3,
                "consent_unavailable": 1,
                "extractor_failure_contained": 1,
                "identity_changed": 1,
                "identity_unavailable": 1,
                "source_unavailable": 1,
                "source_version_changed": 1,
            },
            "hard_invariants": {
                "automatic_active": 0,
                "automatic_user_confirmed": 0,
                "cross_principal_write": 0,
                "privacy_artifact_hit": 0,
                "public_knowledge_write": 0,
                "without_consent_proposal": 0,
            },
            "cleanup_residue": 0,
        },
        "quality": {
            "reviewed_count": 300,
            "label_counts": {"correct": 285, "unsupported": 3},
            "privacy_sensitive_count": 0,
            "stale_source_accepted_count": 0,
            "quality_gate": "PASS",
        },
        "lifecycle": {
            "confirmed_count": 1,
            "superseded_count": 1,
            "rejected_count": 1,
            "selected_after_revoke": 0,
            "fact_residue": 0,
            "consent_residue": 0,
            "race_matrix": {"unsafe_race_write_count": 0},
        },
        "read": {
            "sample_count": 300,
            "scenario_counts": {
                "conflict": 38,
                "deleted_source": 38,
                "expired": 37,
                "fact_cap": 37,
                "revoked_consent": 38,
            },
            "source_fact_count": 337,
            "would_select_count": 149,
            "conflict_count": 38,
            "hard_invariants": {
                "provider_context_mutation": 0,
                "provider_request_mutation": 0,
                "question_score_report_mutation": 0,
                "cross_principal_selected": 0,
                "consent_revoked_selected": 0,
                "revoked_expired_deleted_selected": 0,
                "unconfirmed_selected": 0,
                "fact_token_limit_violation": 0,
            },
            "read_shadow_p95_latency_ms": 564.684,
            "baseline_p95_latency_ms": 500.0,
            "latency_regression_ratio": 0.129368,
            "provider_calls": 0,
            "cleanup_residue": 0,
        },
    }
