from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class PrincipalMemoryConsentStore(Protocol):
    def get_current(self, *, deployment_id: str, principal_id: str): ...
    def grant(self, consent): ...
    def revoke(self, *, deployment_id: str, principal_id: str, revoked_at): ...
    def purge(self, *, deployment_id: str, principal_id: str) -> int: ...
